image: docker:stable-dind

stages:
  - dependency
  - build

cache:
  key: ".cache-${CI_COMMIT_REF_SLUG}"
  paths:
  - .cache-composer-cache/
  - vendor/

base:build-base-php-thesis:
  when: manual
  stage: dependency
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:

    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}, \"https://index.docker.io/v1/\":{\"auth\":\"SECRET\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.build/base_php_8.1/Dockerfile --destination $CI_REGISTRY_IMAGE/base-php-8.1/thesis:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE/base-php-8.1/thesis:$CI_COMMIT_SHORT_SHA
  only:
    - master
    - branches

dependency:composer-install-thesis:
  stage: dependency
  cache:
    policy: push
    key: ".cache-${CI_COMMIT_REF_SLUG}"
    paths:
    - .cache-composer-cache/
    - vendor/
  image: docker.io/library/composer:latest
  before_script:
  - composer config -g cache-dir "$(pwd)/.cache-composer-cache"
  - composer config repo.packagist composer https://packagist.org
  script:
  - composer install --ignore-platform-reqs --dev --optimize-autoloader --no-ansi --no-interaction --no-progress --no-scripts
  - composer require backpack/basset --no-scripts
  only:
  - master
  - branches

build:build-php-thesis:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  cache:
    policy: pull
    key: ".cache-${CI_COMMIT_REF_SLUG}"
    paths:
    - .cache-composer-cache/
    - vendor/
  script:
    # - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}, \"https://index.docker.io/v1/\":{\"auth\":\"SECRET\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.build/sleep_app_php/Dockerfile --destination $CI_REGISTRY_IMAGE/thesis:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE/thesis:$CI_COMMIT_SHORT_SHA
  only:
    - master
    - branches
    
build:build-nginx-thesis:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.build/nginx/Dockerfile --destination $CI_REGISTRY_IMAGE/thesis/nginx:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE/thesis/nginx:$CI_COMMIT_SHORT_SHA
  only:
  - master
  - branches
